import turtle
pen=turtle.Turtle()
turtle.bgcolor("black")

pen.speed(20)
pen.pensize(5)

pen.setposition(0,-280)
pen.pendown()
pen.begin_fill()
pen.color('red')
pen.pencolor('white')
pen.circle(300)
pen.end_fill()
pen.penup()

pen.setposition(0,-230)
pen.pendown()
pen.begin_fill()
pen.color('red')
pen.pencolor('white')
pen.circle(250)
pen.end_fill()
pen.penup()

pen.penup()
pen.setposition(-120,250)
pen.rt(90)
pen.pendown()
pen.fillcolor('darkred')
pen.begin_fill()
pen.forward(540)
pen.left(90)
pen.forward(90)
pen.left(270)
pen.bk(250)
pen.lt(50)
pen.forward(350)
pen.left(80)
pen.forward(80)
pen.left(100)
pen.forward(350)
pen.rt(100)
pen.forward(350)
pen.left(100)
pen.forward(80)
pen.rt(-80)
pen.forward(350)
pen.left(50)
pen.bk(198)
pen.rt(85)
pen.fd(92)
pen.end_fill()
pen.penup()

turtle.done()
