from turtle import *
import turtle
import tkinter as tk
from tkinter import font
from PIL import ImageTk,Image
from tkinter import messagebox
def logo():
    bgcolor("peach puff")
    hideturtle()
    pensize(2)
    pencolor("gold") 
    penup()
    setpos(50,100)
    pendown()
    lt(90)
    circle(70,180)
    penup()

    penup()
    setpos(-90,75)
    pendown()
    pensize(2)
    speed(20)
    pencolor("gold")
    lt(360)
    circle(70,180)

    penup()
    setpos(70,100)
    pendown()
    pensize(5)
    speed(20)
    pencolor("gold")
    lt(360)
    circle(90,180)
    penup()

    penup()
    setpos(-110,75)
    pendown()
    pensize(5)
    speed(20)
    pencolor("gold")
    lt(-359)
    circle(90,180)
    penup()

    pensize(5)
    pencolor("black")
    speed(20)
    penup()
    setpos(-65,30)
    pendown()
    lt(270)
    fd(90)
    lt(80)
    fd(70)

    pensize(4)
    pencolor("black")
    tracer(20)
    penup()
    setpos(38,104)
    pendown()
    lt(400)
    circle(15,150)
    lt(5)
    fd(20)
    lt(10)
    bk(30)
    lt(200)
    circle(30,150)
    lt(5)
    fd(20)
    lt(10)
    bk(30)
    lt(200)
    circle(15,150)
    rt(-10)
    fd(53)
    
    pensize(2)
    pencolor("black")
    speed(20)
    penup()
    setpos(10,90)
    pendown()
    begin_fill()
    color("black")
    lt(150)
    fd(50)
    lt(90)
    fd(10)
    lt(90)
    fd(40)
    end_fill()

    pensize(3)
    pencolor("black")
    speed(20)
    penup()
    setpos(-45,80)
    pendown()
    begin_fill()
    color("black")
    lt(205)
    fd(50)
    lt(90)
    fd(10)
    lt(90)
    fd(40)
    end_fill()

    penup()
    setpos(-35,50)
    pendown()
    pencolor("brown")
    write("K2",font=("forte",20,"bold"))

    pensize(3)
    pencolor("dark green")
    speed(20)
    penup()
    setpos(60,85)
    pendown()
    begin_fill()
    color("dark green")
    lt(90)
    circle(5)
    end_fill()

    pensize(3)
    pencolor("dark green")
    speed(20)
    penup()
    setpos(-95,88)
    pendown()
    begin_fill()
    color("dark green")
    lt(90)
    circle(5)
    end_fill()

    penup()
    setpos(-100,-50)
    pendown()
    pencolor("brown")
    write("RESTAURANT",font=("forte",20,"bold"))
logo()
done()
def main_page():
    root=tk.Tk()
    root.geometry("900x500")
    frame=tk.Frame(root,width=500,height=500)
    frame.place(relx=0.03,rely=0.00)
    img=ImageTk.PhotoImage(Image.open("pizza.jpg"))
    label=tk.Label(frame,image=img).pack()
    
    frame1=tk.Frame(root,bg="black",height=30,width=1600).place(rely=0.00)
    frame2=tk.Frame(root,bg="black",height=1600,width=45).place(rely=0.00)
    mani=tk.Label(root,text="HOME",bg="black",fg="white")
    mani1=tk.Label(root,text="CONTACT",bg="black",fg="white")
    mani2=tk.Label(root,text="ABOUT",bg="black",fg="white")
    mani3=tk.Label(root,text="MENU",bg="black",fg="white")
    mani.place(relx=0.01,rely=0.01)
    mani1.place(relx=0.05,rely=0.01)
    mani2.place(relx=0.10,rely=0.01)
    mani3.place(relx=0.15,rely=0.01)
    ff=font.Font(weight="bold",family="times new roman",size=15)
    t="""OPEN:MONDAY TO FRIDAY
                 1PM TO 10PM"""
    tk.Label(root,text=t,font=ff,bg="black",fg="white").place(relx=0.05,rely=0.90)
    f=font.Font(weight="bold",family="times new roman",size=20)
    kk="""FOOD that makes 
               you say WOW"""
    tk.Label(root,text=kk,font=f,bg="black",fg="white").place(relx=0.40,rely=0.40)
    frame3=tk.Frame(root,bg="black",height=1600,width=55).place(relx=0.96,rely=0.00)
    root.mainloop()
main_page()

'''def resister():
    login_frame.pack_forget()
    regis_frame.pack(fill="both",expand=True)
'''

